### ISSUE TITLE
output data

### ISSUE THREAD

**Issue by aremazeilles** [madrob-beast/madrob_beast_pi#9]
The idea is to insert in the repository examples of input data, and associated output data.
That will enable us to insert later on some automatic testing of the docker image generated.
In other repo, I am inserting the docker image generation within docker action (example [here](https://github.com/eurobench/pi_bullet/tree/master/.github/workflows)

So it would be needed to place in test_data:

* all input files in a folder`input`
* related resulting files in a folder `output`
  * we may need organizing the input & or output per project /pi, to be clarified later on

**Comment by Enri2077** [comment]
Ok. I'll upload the input/output once we know the folder structure.

**Comment by Enri2077** [comment]
Should we use the same structure as this https://github.com/eurobench/pi_bullet/tree/master/tests ?

**Comment by aremazeilles** [comment]
Something similar yes. Have a look at the test plan we use (xml in the link you provided):
We generate one test per pi algorithm, and then we expect having a folder containing the output pi files, so that we can check they are all identical.  
That constrains the output structure: one folder per call.
The input can be slightly different: if all pi from a protocol use similar files (like taken from one run of the experiment), then it is good to place them all together. Actually better, so that we can have a clear view of data collected during one run.

We can have different input folder for examples if you are checking different settings or conditions, or at least to distinguish the madrob and the beast case.

**Comment by aremazeilles** [comment]
ping

**Comment by Enri2077** [comment]
Hi Anthony, I'll work on this and the other issues next week. Sorry for making you wait.

**Comment by Enri2077** [comment]
I changed the directory structure for the test data and generated the output files.
I only have the data for Madrob. The data for beast is not available yet due to delay of the hardware (but I hope we'll be progressing with beast in the next weeks).

I also added the xml, but the value of `pi_name` still does not correspond to the actual name. This depends on how I proceed with the docker images issue (https://github.com/madrob-beast/madrob_beast_pi/issues/10). I think I'll try to make it similar to the bullet_pi.

**Comment by Enri2077** [comment]
I'll close this issue once I figure out the naming.

**Comment by Enri2077** [comment]
I updated the test xml.
One last thing, we were adding a timestamp to the PI output file to avoid overwriting them.
I assumed you don't want this since you'll never know the PI filenames and removed the timestamp (https://github.com/madrob-beast/madrob_beast_pi/commit/0c65786f7792a2f190d0791a777f377e69721159).
